version: "3"

services:
  broker:
    image: vromero/activemq-artemis:2.11.0-alpine
    environment: 
      - ARTEMIS_USERNAME=quarkus
      - ARTEMIS_PASSWORD=quarkus
    ports: 
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    networks: 
      - biwi-net
  scheduleddb:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=scheduled
      - POSTGRES_DB=scheduleddb
    ports:
      - "5433:5432"
    networks:
      - biwi-net

networks:
  biwi-net:
    driver: bridge