DROP DATABASE IF EXISTS scheduleddb;
DROP DATABASE IF EXISTS biwidesc;
CREATE DATABASE scheduleddb;
CREATE DATABASE biwidesc;
GRANT ALL PRIVILEGES ON DATABASE scheduleddb TO hibernate;
GRANT ALL PRIVILEGES ON DATABASE biwidesc TO hibernate;