---
- hosts: all
  become: yes
  roles:
    - docker

- hosts: machine-1
  become: yes
  roles:
    - role: docker-swarm
      vars:
        create: 'true'
        type: 'manager'
        network_name: 'biwi-net'

- hosts:
  - machine-2
  - machine-3
  become: yes
  roles:
    - role: docker-swarm
      vars:
        create: 'false'
        type: 'worker'
