---
- hosts: all
  become: yes
  roles:
    - docker
  tasks:
    - name: Increase vm.max_map_count
      sysctl:
        name: vm.max_map_count
        value: '262144'
        sysctl_set: yes
        state: present

- hosts: machine-1
  become: yes
  roles:
    - role: docker-swarm
      vars:
        create: 'true'
        type: 'manager'
        network_name: 'biwi-net'

- hosts:
  - machine-2
  - machine-3
  become: yes
  roles:
    - role: docker-swarm
      vars:
        create: 'false'
        type: 'worker'

- hosts: all
  become: yes
  tasks:
    - name: Create metricbeat directory structure
      file:
        path: /opt/metricbeat
        state: directory
        mode: u=r
    - name: Copy metricbeat configuration file to all hosts
      template:
        src: "roles/monitoring/templates/metricbeat.yml.j2"
        dest: "/opt/metricbeat/metricbeat.yml"
    - name: Create postgresql directory structure
      file:
        path: /opt/postgresql/sql
        state: directory
        mode: u=r
    - name: Copy sql files to all hosts
      copy:
        src: "roles/services/templates/initdbs.sql"
        dest: "/opt/postgresql/sql/initdbs.sql"
        force: yes
    - name: Create keycloak directory
      file:
        path: /opt/keycloak
        state: directory
        mode: u=r
    - name: Copy keycloak conf file to all hosts
      copy:
        src: "roles/services/templates/biwi_realm.json"
        dest: "/opt/keycloak/biwi_realm.json"

- hosts:
  - machine-1
  become: yes
  roles:
    - monitoring
    - services
